In [ ]:
pd.Series([80,90,70])

0    80
1    90
2    70
dtype: int64

In [ ]:
df['Marks'][0]

np.int64(80)

In [ ]:
marks = pd.Series([85, 92, 67, 74])
print(marks)

0    85
1    92
2    67
3    74
dtype: int64

In [ ]:
marks[0]

np.int64(85)

Series     → one column

DataFrame  → complete table

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Ali", "Sara", "Ahmed"],
    "Marks": [80, 90, 70],
    "Age": [20, 21, 19]
})

print(df)

    Name  Marks  Age
0    Ali     80   20
1   Sara     90   21
2  Ahmed     70   19

In [ ]:
df.head()

    Name  Marks  Age
0    Ali     80   20
1   Sara     90   21
2  Ahmed     70   19

In [ ]:
df.tail()

    Name  Marks  Age
0    Ali     80   20
1   Sara     90   21
2  Ahmed     70   19

In [ ]:
df.shape

(3, 3)

In [ ]:
df.columns

Index(['Name', 'Marks', 'Age'], dtype='object')

In [ ]:
df.dtypes

Name     object
Marks     int64
Age       int64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Marks   3 non-null      int64
 2   Age     3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

pandas cheatcode
pd.Series()       → one column

pd.DataFrame()    → table

df.head()         → first rows

df.tail()         → last rows

df.shape          → (rows, columns)

df.columns        → column names

df.dtypes         → data types

df.info()         → DataFrame overview

In [ ]:
print(df["Age"])

0    20
1    21
2    19
Name: Age, dtype: int64

In [ ]:
print(df[["Name", "Age"]])

    Name  Age
0    Ali   20
1   Sara   21
2  Ahmed   19

In [ ]:
df.loc[1]

Name     Sara
Marks      90
Age        21
Name: 1, dtype: object

In [ ]:
df.iloc[1]

Name     Sara
Marks      90
Age        21
Name: 1, dtype: object

The cheat code

loc → LABEL / index

iloc → INTEGER POSITION

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Ali", "Sara", "Ahmed", "Zara"],
    "Marks": [80, 90, 70, 95],
    "Age": [20, 21, 19, 22]
})

print(df)

    Name  Marks  Age
0    Ali     80   20
1   Sara     90   21
2  Ahmed     70   19
3   Zara     95   22

In [ ]:
df[df["Marks"] > 80]

   Name  Marks  Age
1  Sara     90   21
3  Zara     95   22

In [ ]:
df[df["Age"] < 21]

    Name  Marks  Age
0    Ali     80   20
2  Ahmed     70   19

Suppose we want:

Students whose Marks are greater than 80 AND Age is less than 22

In [ ]:
df[(df["Marks"] > 80) & (df["Age"] < 22)]

   Name  Marks  Age
1  Sara     90   21

In [ ]:
df[(df["Marks"] > 80) | (df["Age"] < 20)]

    Name  Marks  Age
1   Sara     90   21
2  Ahmed     70   19
3   Zara     95   22

In [ ]:
df["Passed"] = (df["Marks"] >= 50) & (df['Age'] > 20)

In [ ]:
print(df)

    Name  Marks  Age  Passed
0    Ali     85   20   False
1   Sara     95   21    True
2  Ahmed     75   19   False
3   Zara    100   22    True

In [ ]:
df["Marks"] = df["Marks"] + 5

In [ ]:
print(df)

    Name  Marks  Age  Passed
0    Ali     90   20   False
1   Sara    100   21    True
2  Ahmed     80   19   False
3   Zara    105   22    True

In [ ]:
df.sort_values("Marks")

    Name  Marks  Age  Passed
2  Ahmed     80   19   False
0    Ali     90   20   False
1   Sara    100   21    True
3   Zara    105   22    True

In [ ]:
df.sort_values("Marks", ascending=False)

    Name  Marks  Age  Passed
3   Zara    105   22    True
1   Sara    100   21    True
0    Ali     90   20   False
2  Ahmed     80   19   False

In [ ]:
df.sort_values("Age", ascending=False)

    Name  Marks  Age  Passed
3   Zara    105   22    True
1   Sara    100   21    True
0    Ali     90   20   False
2  Ahmed     80   19   False

In [ ]:
df = pd.DataFrame({
    "Name": ["Ali", "Sara", "Ahmed", "Zara"],
    "Marks": [80, 90, None, 95],
    "Age": [20, None, 19, 22]
})

print(df)

    Name  Marks   Age
0    Ali   80.0  20.0
1   Sara   90.0   NaN
2  Ahmed    NaN  19.0
3   Zara   95.0  22.0

In [ ]:
df.isna()

    Name  Marks    Age
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False

In [ ]:
df.isna().sum()

Name     0
Marks    1
Age      1
dtype: int64

In [ ]:
df.dropna()

   Name  Marks   Age
0   Ali   80.0  20.0
3  Zara   95.0  22.0

In [ ]:
df["Age"] = df["Age"].fillna(0)

In [ ]:
df["Marks"] = df["Marks"].fillna(0)

In [ ]:
print(df)

    Name  Marks   Age
0    Ali   80.0  20.0
1   Sara   90.0   NaN
2  Ahmed    0.0  19.0
3   Zara   95.0  22.0

isna()    → Find missing values

dropna()  → Remove missing values

fillna()  → Replace missing values

In [ ]:
df["Age"].fillna(20)

0    20.0
1    20.0
2    19.0
3    22.0
Name: Age, dtype: float64

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Ali", "Sara", "Ahmed", "Zara", "Ali"],
    "Marks": [80, 90, 70, 95, 80],
    "City": ["Peshawar", "Lahore", "Peshawar", "Karachi", "Peshawar"]
})

In [3]:
df["Marks"].unique()

array([80, 90, 70, 95])

groupby() = split data into groups → perform calculation on each group.

In [4]:
df = pd.DataFrame({
    "Name": ["Ali", "Sara", "Ahmed", "Zara", "Hamza"],
    "City": ["Peshawar", "Lahore", "Peshawar", "Lahore", "Peshawar"],
    "Marks": [80, 90, 70, 95, 85]
})

In [5]:
df.groupby("City")["Marks"].mean()

City
Lahore      92.500000
Peshawar    78.333333
Name: Marks, dtype: float64

In [7]:
df.groupby("City")["Marks"].sum()

City
Lahore      185
Peshawar    235
Name: Marks, dtype: int64

In [8]:
df.groupby("City")["Marks"].max()

City
Lahore      95
Peshawar    85
Name: Marks, dtype: int64

In [9]:
df.groupby("City")["Marks"].min()

City
Lahore      90
Peshawar    70
Name: Marks, dtype: int64

In [10]:
df.groupby("City")["Marks"].count()

City
Lahore      2
Peshawar    3
Name: Marks, dtype: int64

In [11]:
df1 = pd.DataFrame({
    "Name": ["Ali", "Sara"],
    "Marks": [80, 90]
})

df2 = pd.DataFrame({
    "Name": ["Ahmed", "Zara"],
    "Marks": [70, 95]
})

In [13]:
result = pd.concat([df1, df2])

In [14]:
print(result)

    Name  Marks
0    Ali     80
1   Sara     90
0  Ahmed     70
1   Zara     95

In [15]:
result = pd.concat([df1, df2] , ignore_index=True)

In [16]:
print(result)

    Name  Marks
0    Ali     80
1   Sara     90
2  Ahmed     70
3   Zara     95

merge() — combine using a common column

In [17]:
students = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Ali", "Sara", "Ahmed"]
})

marks = pd.DataFrame({
    "ID": [1, 2, 3],
    "Marks": [80, 90, 70]
})

In [18]:
result = pd.merge(students, marks, on="ID")

In [19]:
print(result)

   ID   Name  Marks
0   1    Ali     80
1   2   Sara     90
2   3  Ahmed     70

concat() → stack/combine DataFrames.

merge() → join DataFrames using a common column/key.

In [21]:
# DATATYPES
df.dtypes

Name     object
City     object
Marks     int64
dtype: object

In [23]:

df["Age"] = df["Age"].astype(int)

Reading & writing files

This is essential because real datasets usually come from files.

**CSV**

In [ ]:
df = pd.read_csv("students.csv")

In [ ]:
df.to_csv("students.csv", index=False)

**JSON**

In [ ]:
df = pd.read_json("students.json")

In [ ]:
df.to_json("students.json", orient="records")

**EXCEL**

In [ ]:
df = pd.read_excel("students.xlsx")

In [ ]:
df.to_excel("students.xlsx", index=False)